BeginnerBasics/Readme.md
pytorch/README.md
pyttsx3/README.md
skiPy/README.md
sklearn/README.md
turtle/README.md

Markdown changes have been made to the following folders:
-BeginnerBasics
-pyttsx3
-Pytorch
-skiPy
-sklearn
-Turtle

Updated Readme.md for folders

---

pyqt5/basicwindow.py

added a code to create a basic window in pyqt5

created code to create basic window

---

network.ipynb
pytorch/network.py

To build a simple neural network using Pytorch.

Neural network using Pytorch

---

Pandas/data.py
dataframeipynb

To construct a DataFrame in Pandas using string data

Construct a DataFrame in Pandas using string data

---

Numpy/Polynomial_Operations/Polymul.ipynb

Created using Colaboratory

---

skiPy/Determinants.ipynb
skiPy/Eigen_values_and_eigen_vectors.ipynb

find out determinants using scipy

Determinants 

---

skiPy/Double_Integrals.ipynb
skiPy/Single_Integrals.ipynb
skiPy/Solving_systems_of_linear_equations.ipynb

Solving systems of linear equations

Solving systems of linear equations

---

Math/Area_of_a_Circle.ipynb
Math/Circumference_of_circle.ipynb
Math/Isclose.ipynb
Math/Temperature_Converter.ipynb

Temperature Converter

---

pyTelegramAPI/Define_functions_for_operation.ipynb

Define functions for operation

Define functions for operation

---

Json/Convert_from_JSON_to_Python.ipynb
Json/Convert_from_Python_to_JSON.ipynb
pyTelegramAPI/Adding_functionalities_to_the_Bot.ipynb
pyTelegramAPI/Adding_the_Handlers_to_handle_our_messages_and_commands.ipynb

Adding some more functionalities to the Bot

Adding some more functionalities to the Bot

---

Json/Complex_Encoding.ipynb
Json/Converting_Python_object_containing_all_the_legal_data_types.ipynb
Json/Extending.ipynb
Json/Format_the_Result.ipynb
Json/Order_the_Result.ipynb

Convert a Python object containing all the legal data types

Convert a Python object containing all the legal data types

---

Json/Writing_JSON_to_a_file.ipynb

Writing JSON to a file

---

pandas/Load_a_CSV_file_into_a_Pandas_DataFrame.ipynb

Load a CSV file into a Pandas DataFrame

Load a CSV file into a Pandas DataFrame

---

pandas/Creating_a_Series.ipynb
pandas/Load_a_CSV_file_into_a_Pandas_DataFrame.ipynb

Creating a Series

---

Creating a DataFrame/Creating_a_DataFrame.ipynb
pandas/Load_a_CSV_file_into_a_Pandas_DataFrame.ipynb

Creating a DataFrame in pandas

Creating a DataFrame

---

Datetime/Handling_timezone_in_Python.ipynb
Datetime/Time_object_to_represent_time.ipynb
Datetime/strptime().ipynb
sklearn/Loading_a_dataset.ipynb

Handling timezone in Python

---

Datetime/Time_object_to_represent_time.ipynb
Datetime/strptime().ipynb
sklearn/Loading_a_dataset.ipynb

Loading a dataset

---

Datetime/Difference_between_two_timedelta_objects.ipynb
Datetime/Time_object_to_represent_time.ipynb
sklearn/Loading_a_dataset.ipynb

Difference between two timedelta objects

Difference between two timedelta objects

---

Datetime/Format_date_using_strftime().ipynb
Datetime/Time_object_to_represent_time.ipynb
sklearn/Loading_a_dataset.ipynb

Format date using strftime()

---

Datetime/Printing_negative_timedelta_object.ipynb
Datetime/Time_object_to_represent_time.ipynb
sklearn/Loading_a_dataset.ipynb

Printing negative timedelta object

Printing negative timedelta object

---

Datetime/Difference_between_two_dates_and_times.ipynb
Datetime/Time_object_to_represent_time.ipynb
sklearn/Loading_a_dataset.ipynb

Difference between two dates and times

Difference between two dates and times

---

Datetime/Print_year,_month,_hour,_minute_and_timestamp.ipynb
Datetime/Time_object_to_represent_time.ipynb
sklearn/Loading_a_dataset.ipynb

Print year, month, hour, minute and timestamp

Print year, month, hour, minute and timestamp

---

sklearn/Loading_a_dataset.ipynb
sklearn/Splitting_the_dataset.ipynb

 Splitting the dataset

---

sklearn/DataFrame.ipynb
sklearn/Loading_a_dataset.ipynb

sklearn DataFrame
